name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Docker (if not already available)
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Build APK using stable Buildozer Docker image
      run: |
        docker run --rm -v ${{ github.workspace }}:/app \
          -w /app kivy/buildozer:stable \
          buildozer android debug

    - name: Upload built APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
